<Project>
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <Nullable>disable</Nullable>
    <Deterministic>true</Deterministic>
    <Version>1.7.2</Version>
    <AssemblyVersion>1.7.2.0</AssemblyVersion>
    <FileVersion>1.7.2.0</FileVersion>
    <BannerlordReferenceVersion>1.3.15.110062</BannerlordReferenceVersion>
    <HarmonyVersion>2.4.2</HarmonyVersion>
  </PropertyGroup>
</Project>
